# Generated by Django 5.0.4 on 2024-04-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_app', '0004_alter_tutor_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
